language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  include:
    - php: 7.0
      env: COVERAGE=yes
  allow_failures:
    - php: hhvm
    - php: nightly
  fast_finish: true

before_install:
  - if [[ $TRAVIS_PHP_VERSION != hhvm && $COVERAGE != yes ]]; then phpenv config-rm xdebug.ini; fi;
  - composer self-update

install:
  - composer install --prefer-dist --no-interaction

script:
  - if [[ $COVERAGE = yes ]]; then bin/phpunit --verbose; else bin/phpunit --verbose --no-coverage; fi

after_script:
  - if [[ $COVERAGE = yes ]]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover build/coverage.xml; fi
